.TH "src Directory Reference" 3 "Fri Jan 6 2017" "STL_SUBDIVISION_LIBRARY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmesh\&.cpp\fP"
.br
.RI "\fIMethod Source for the 'Mesh' Class\&. \fP"
.ti -1c
.RI "file \fBstlsubdiv\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtriangle\&.cpp\fP"
.br
.RI "\fIMethod Source for the 'Triangle' Class\&. \fP"
.ti -1c
.RI "file \fBvector3d\&.cpp\fP"
.br
.RI "\fISource for the 'Vector3d' class\&. \fP"
.in -1c
