.TH "include Directory Reference" 3 "Fri Jan 6 2017" "STL_SUBDIVISION_LIBRARY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmesh\&.hpp\fP"
.br
.RI "\fIHeader for the 'Mesh' class\&. \fP"
.ti -1c
.RI "file \fBtriangle\&.hpp\fP"
.br
.RI "\fIHeader for the 'Triangle' class\&. This is the expression of an stl face\&. \fP"
.ti -1c
.RI "file \fBvector3d\&.hpp\fP"
.br
.RI "\fIHeader for the 'Vector3d' class\&. \fP"
.in -1c
