.TH "kia" 3 "Fri Jan 6 2017" "STL_SUBDIVISION_LIBRARY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kia \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMesh\fP"
.br
.RI "\fIThe 'Mesh' class is the master class for the STL meshes\&. It includes the original user input mesh, methods to load this and subdivide it into a finer stl mesh\&. The subdivision does not alter the overall geometry, this is not a smoothing utility\&. It is also important to note that the exact size of the final triangles is undefined, only the maximum triangle size is specified\&. \fP"
.ti -1c
.RI "class \fBTriangle\fP"
.br
.RI "\fIThe 'Triangle' class defines exactly 1 triangle as used by an STL\&. STL files are described as vectors of 'Triangles'\&. \fP"
.ti -1c
.RI "class \fBVector3d\fP"
.br
.RI "\fIThe 'Vector3d' class defines a simple 3d vector\&. This is really a glorified structure\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &_out, \fBTriangle\fP const &_data)"
.br
.ti -1c
.RI "\fBVector3d\fP \fBcrossProduct\fP (\fBVector3d\fP _v1, \fBVector3d\fP _v2)"
.br
.RI "\fIThis function uses the Vector3D class to implement the cross product of two vectors\&. This is useful for finding areas\&. The result is the cross of v1 x v2\&. \fP"
.ti -1c
.RI "double \fBvector3dAbsolute\fP (\fBVector3d\fP _v)"
.br
.RI "\fIGet absolute magnitude of the vector\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBVector3d\fP kia::crossProduct (Vector3d_v1, Vector3d_v2)"

.PP
This function uses the Vector3D class to implement the cross product of two vectors\&. This is useful for finding areas\&. The result is the cross of v1 x v2\&. 
.PP
 
.PP
\fBParameters:\fP
.RS 4
\fI_v1\fP --- vector 1 
.br
\fI_v2\fP --- vector 2 
.RE
.PP
\fBReturns:\fP
.RS 4
the cross-product of _v1 x _v2 
.RE
.PP

.SS "std::ostream & kia::operator<< (std::ostream &_out, Triangle const &_data)"

.SS "double kia::vector3dAbsolute (Vector3d_v)"

.PP
Get absolute magnitude of the vector\&. 
.PP
 
.PP
\fBParameters:\fP
.RS 4
\fI_v\fP the vector in question 
.RE
.PP
\fBReturns:\fP
.RS 4
The magnitude of the vector\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for STL_SUBDIVISION_LIBRARY from the source code\&.
