.TH "kia::Vector3d" 3 "Fri Jan 6 2017" "STL_SUBDIVISION_LIBRARY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kia::Vector3d \- 
.PP
The 'Vector3d' class defines a simple 3d vector\&. This is really a glorified structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vector3d\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVector3d\fP ()"
.br
.ti -1c
.RI "\fBVector3d\fP (double _x, double _y, double _z)"
.br
.ti -1c
.RI "\fB~Vector3d\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.ti -1c
.RI "double \fBz\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The 'Vector3d' class defines a simple 3d vector\&. This is really a glorified structure\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "kia::Vector3d::Vector3d ()"

.SS "kia::Vector3d::Vector3d (double_x, double_y, double_z)"

.SS "kia::Vector3d::~Vector3d ()"

.SH "Member Data Documentation"
.PP 
.SS "double kia::Vector3d::x"

.SS "double kia::Vector3d::y"

.SS "double kia::Vector3d::z"


.SH "Author"
.PP 
Generated automatically by Doxygen for STL_SUBDIVISION_LIBRARY from the source code\&.
