.TH "include/mesh.hpp" 3 "Fri Jan 6 2017" "STL_SUBDIVISION_LIBRARY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/mesh.hpp \- 
Header for the 'Mesh' class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <triangle\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBkia::Mesh\fP"
.br
.RI "\fIThe 'Mesh' class is the master class for the STL meshes\&. It includes the original user input mesh, methods to load this and subdivide it into a finer stl mesh\&. The subdivision does not alter the overall geometry, this is not a smoothing utility\&. It is also important to note that the exact size of the final triangles is undefined, only the maximum triangle size is specified\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBkia\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Header for the 'Mesh' class\&. 

KUKA INNOVATION AWARD Perception -- STL Subdivision
.PP
\fBAuthor:\fP
.RS 4
Iain Brookshaw 
.RE
.PP
\fBDate:\fP
.RS 4
02 December 2016 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for STL_SUBDIVISION_LIBRARY from the source code\&.
