.TH "src/stlsubdiv.cpp" 3 "Fri Jan 6 2017" "STL_SUBDIVISION_LIBRARY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/stlsubdiv.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <mesh\&.hpp>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOUT\fP   std::cout << '[STL]: '"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBusage\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define OUT   std::cout << '[STL]: '"

.SH "Function Documentation"
.PP 
.SS "int main (intargc, char **argv)"

.SS "void usage ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for STL_SUBDIVISION_LIBRARY from the source code\&.
