.TH "todo" 3 "Fri Jan 6 2017" "STL_SUBDIVISION_LIBRARY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 

.IP "\fBMember \fBkia::Mesh::subdivide\fP (Triangle *_in_face_ptr, std::vector< Triangle > *_out_faces_ptr)\fP" 1c
recursion safety: un-Hardwire this\&. Some faces might be very big 
.PP

