.TH "include/triangle.hpp" 3 "Fri Jan 6 2017" "STL_SUBDIVISION_LIBRARY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/triangle.hpp \- 
.PP
Header for the 'Triangle' class\&. This is the expression of an stl face\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <vector3d\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBkia::Triangle\fP"
.br
.RI "\fIThe 'Triangle' class defines exactly 1 triangle as used by an STL\&. STL files are described as vectors of 'Triangles'\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBkia\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBkia::operator<<\fP (std::ostream &_out, Triangle const &_data)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Header for the 'Triangle' class\&. This is the expression of an stl face\&. 

KUKA INNOVATION AWARD Perception -- STL Subdivision
.PP
\fBAuthor:\fP
.RS 4
Iain Brookshaw 
.RE
.PP
\fBDate:\fP
.RS 4
02 December 2016 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for STL_SUBDIVISION_LIBRARY from the source code\&.
