.TH "src/triangle.cpp" 3 "Fri Jan 6 2017" "STL_SUBDIVISION_LIBRARY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/triangle.cpp \- 
.PP
Method Source for the 'Triangle' Class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <triangle\&.hpp>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBkia\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBkia::operator<<\fP (std::ostream &_out, Triangle const &_data)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Method Source for the 'Triangle' Class\&. 

KUKA INNOVATION AWARD Perception -- STL Subdivision
.PP
\fBAuthor:\fP
.RS 4
Iain Brookshaw 
.RE
.PP
\fBDate:\fP
.RS 4
02 December 2016 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for STL_SUBDIVISION_LIBRARY from the source code\&.
