.TH "include/vector3d.hpp" 3 "Fri Jan 6 2017" "STL_SUBDIVISION_LIBRARY" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/vector3d.hpp \- 
.PP
Header for the 'Vector3d' class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <math\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBkia::Vector3d\fP"
.br
.RI "\fIThe 'Vector3d' class defines a simple 3d vector\&. This is really a glorified structure\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBkia\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Vector3d \fBkia::crossProduct\fP (Vector3d _v1, Vector3d _v2)"
.br
.RI "\fIThis function uses the Vector3D class to implement the cross product of two vectors\&. This is useful for finding areas\&. The result is the cross of v1 x v2\&. \fP"
.ti -1c
.RI "double \fBkia::vector3dAbsolute\fP (Vector3d _v)"
.br
.RI "\fIGet absolute magnitude of the vector\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Header for the 'Vector3d' class\&. 

KUKA INNOVATION AWARD Perception -- STL Subdivision
.PP
\fBAuthor:\fP
.RS 4
Iain Brookshaw 
.RE
.PP
\fBDate:\fP
.RS 4
02 December 2016 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for STL_SUBDIVISION_LIBRARY from the source code\&.
